In [1]:
import pandas as pd

In [2]:
pd.__version__

'1.1.3'

In [3]:
# Create Dataframe
df=pd.DataFrame([11,22,33],columns=['Col_name'])
print(df)

   Col_name
0        11
1        22
2        33

In [4]:
print(type(df))

<class 'pandas.core.frame.DataFrame'>

In [6]:
Data={
    'Name':['Mathav','Vishaka','Lalita','Rishabh'],
    'Age':[12,13,14,15],
    'Salary':[20000,30000,40000,50000]
}

In [7]:
df=pd.DataFrame(Data)

In [8]:
df

      Name  Age  Salary
0   Mathav   12   20000
1  Vishaka   13   30000
2   Lalita   14   40000
3  Rishabh   15   50000

In [9]:
# Basic Dataframe Understanding
df.head()

      Name  Age  Salary
0   Mathav   12   20000
1  Vishaka   13   30000
2   Lalita   14   40000
3  Rishabh   15   50000

In [10]:
df.head(2)

      Name  Age  Salary
0   Mathav   12   20000
1  Vishaka   13   30000

In [11]:
df.tail()

      Name  Age  Salary
0   Mathav   12   20000
1  Vishaka   13   30000
2   Lalita   14   40000
3  Rishabh   15   50000

In [13]:
df.shape

(4, 3)

In [14]:
df.columns

Index(['Name', 'Age', 'Salary'], dtype='object')

In [17]:
df.rename(columns={'Salary':'Monthly_Salary'},inplace=True)

In [18]:
df

      Name  Age  Monthly_Salary
0   Mathav   12           20000
1  Vishaka   13           30000
2   Lalita   14           40000
3  Rishabh   15           50000

In [19]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Name            4 non-null      object
 1   Age             4 non-null      int64
 2   Monthly_Salary  4 non-null      int64
dtypes: int64(2), object(1)
memory usage: 224.0+ bytes

In [21]:
df.describe()

             Age  Monthly_Salary
count   4.000000        4.000000
mean   13.500000    35000.000000
std     1.290994    12909.944487
min    12.000000    20000.000000
25%    12.750000    27500.000000
50%    13.500000    35000.000000
75%    14.250000    42500.000000
max    15.000000    50000.000000

In [ ]:
# Save and Load Dataframe from csv

In [26]:
df.to_csv('Test_data.csv',index=False)# dataframne.to_csv,,,,,export dataframe

In [27]:
load_df=pd.read_csv('Test_data.csv')#import dataframe
load_df

      Name  Age  Monthly_Salary
0   Mathav   12           20000
1  Vishaka   13           30000
2   Lalita   14           40000
3  Rishabh   15           50000

In [ ]:
# Rows and Column Selection

In [31]:
#df[['Name']] #single column
df[['Name','Monthly_Salary']]  #

      Name  Monthly_Salary
0   Mathav           20000
1  Vishaka           30000
2   Lalita           40000
3  Rishabh           50000

In [33]:
#Select Rows
df.loc[df.Name=='Lalita']

     Name  Age  Monthly_Salary
2  Lalita   14           40000

In [36]:
df.loc[(df.Name=='Vishaka')&(df.Monthly_Salary>30000)]

Empty DataFrame
Columns: [Name, Age, Monthly_Salary]
Index: []

In [37]:
df.iloc[0] #index value based

Name              Mathav
Age                   12
Monthly_Salary     20000
Name: 0, dtype: object

In [38]:
df.iloc[0:2]

      Name  Age  Monthly_Salary
0   Mathav   12           20000
1  Vishaka   13           30000

In [39]:
df

      Name  Age  Monthly_Salary
0   Mathav   12           20000
1  Vishaka   13           30000
2   Lalita   14           40000
3  Rishabh   15           50000

In [40]:
df['Age']>12

0    False
1     True
2     True
3     True
Name: Age, dtype: bool

In [41]:
 df_age_filter=df[df['Age']>12]
df_age_filter

      Name  Age  Monthly_Salary
1  Vishaka   13           30000
2   Lalita   14           40000
3  Rishabh   15           50000

In [44]:
df[(df['Age']>=12) & (df['Monthly_Salary']>=20000)]

      Name  Age  Monthly_Salary
0   Mathav   12           20000
1  Vishaka   13           30000
2   Lalita   14           40000
3  Rishabh   15           50000

In [46]:
df.where(df['Age']>=13)

      Name   Age  Monthly_Salary
0      NaN   NaN             NaN
1  Vishaka  13.0         30000.0
2   Lalita  14.0         40000.0
3  Rishabh  15.0         50000.0

In [47]:
df.where(df['Age']>=14, other='Not Eligible')

           Name           Age Monthly_Salary
0  Not Eligible  Not Eligible   Not Eligible
1  Not Eligible  Not Eligible   Not Eligible
2        Lalita            14          40000
3       Rishabh            15          50000

In [ ]:
# Rows and Column -Operation

In [49]:
#Add new column
df['Team']=['CEO','HR','CTO','DA']
df

      Name  Age  Monthly_Salary Team
0   Mathav   12           20000  CEO
1  Vishaka   13           30000   HR
2   Lalita   14           40000  CTO
3  Rishabh   15           50000   DA

In [50]:
df['Bonus']=df['Monthly_Salary']*0.2
df

      Name  Age  Monthly_Salary Team    Bonus
0   Mathav   12           20000  CEO   4000.0
1  Vishaka   13           30000   HR   6000.0
2   Lalita   14           40000  CTO   8000.0
3  Rishabh   15           50000   DA  10000.0

In [51]:
#Add new row
df.loc[len(df)]=['ABC',15,25000,'IT',2000]
df

      Name  Age  Monthly_Salary Team    Bonus
0   Mathav   12           20000  CEO   4000.0
1  Vishaka   13           30000   HR   6000.0
2   Lalita   14           40000  CTO   8000.0
3  Rishabh   15           50000   DA  10000.0
4      ABC   15           25000   IT   2000.0

In [52]:
len(df)

5

In [54]:
#Update value-using index name
df.loc[0,'Monthly_Salary']=25000
df

      Name  Age  Monthly_Salary Team    Bonus
0   Mathav   12           25000  CEO   4000.0
1  Vishaka   13           30000   HR   6000.0
2   Lalita   14           40000  CTO   8000.0
3  Rishabh   15           50000   DA  10000.0
4      ABC   15           25000   IT   2000.0

In [58]:
#Update value-using column name
df.loc[df.Name=='Lalita','Monthly_Salary']=45000
df

      Name  Age  Monthly_Salary Team    Bonus  Salary
0   Mathav   12           25000  CEO   4000.0     NaN
1  Vishaka   13           30000   HR   6000.0     NaN
2   Lalita   14           45000  CTO   8000.0     NaN
3  Rishabh   15           50000   DA  10000.0     NaN
4      ABC   15           25000   IT   2000.0     NaN

In [60]:
df.loc[df.Name=='Mathav','Monthly_Salary']=45000
df

      Name  Age  Monthly_Salary Team    Bonus  Salary
0   Mathav   12           45000  CEO   4000.0     NaN
1  Vishaka   13           30000   HR   6000.0     NaN
2   Lalita   14           45000  CTO   8000.0     NaN
3  Rishabh   15           50000   DA  10000.0     NaN
4      ABC   15           25000   IT   2000.0     NaN

In [61]:
#Delete value--row and column
df.drop(df[df.Name=='ABC'].index)  # drop row, axis 0

      Name  Age  Monthly_Salary Team    Bonus  Salary
0   Mathav   12           45000  CEO   4000.0     NaN
1  Vishaka   13           30000   HR   6000.0     NaN
2   Lalita   14           45000  CTO   8000.0     NaN
3  Rishabh   15           50000   DA  10000.0     NaN

In [62]:
[df.Name=='ABC']

[0    False
 1    False
 2    False
 3    False
 4     True
 Name: Name, dtype: bool]

In [63]:
df[df.Name=='ABC']

  Name  Age  Monthly_Salary Team   Bonus  Salary
4  ABC   15           25000   IT  2000.0     NaN

In [70]:
df.drop('Salary',axis=1,inplace=True) # drop column axis=1

KeyError: "['Salary'] not found in axis"

In [71]:
df.drop(['Bonus','Team'],axis=1)

      Name  Age  Monthly_Salary
0   Mathav   12           45000
1  Vishaka   13           30000
2   Lalita   14           45000
3  Rishabh   15           50000
4      ABC   15           25000

In [72]:
df.drop(1,axis=0) # using index va;ue

      Name  Age  Monthly_Salary Team    Bonus
0   Mathav   12           45000  CEO   4000.0
2   Lalita   14           45000  CTO   8000.0
3  Rishabh   15           50000   DA  10000.0
4      ABC   15           25000   IT   2000.0

In [73]:
df

      Name  Age  Monthly_Salary Team    Bonus
0   Mathav   12           45000  CEO   4000.0
1  Vishaka   13           30000   HR   6000.0
2   Lalita   14           45000  CTO   8000.0
3  Rishabh   15           50000   DA  10000.0
4      ABC   15           25000   IT   2000.0

In [78]:
df.rename(columns={'Monthly_Salary':'salary'},inplace=True)
df

      Name  Age  salary Team    Bonus
0   Mathav   12   45000  CEO   4000.0
1  Vishaka   13   30000   HR   6000.0
2   Lalita   14   45000  CTO   8000.0
3  Rishabh   15   50000   DA  10000.0
4      ABC   15   25000   IT   2000.0

In [81]:
df.sort_values('Age')

      Name  Age  salary Team    Bonus
0   Mathav   12   45000  CEO   4000.0
1  Vishaka   13   30000   HR   6000.0
2   Lalita   14   45000  CTO   8000.0
3  Rishabh   15   50000   DA  10000.0
4      ABC   15   25000   IT   2000.0

In [83]:
df.sort_values('salary',ascending=False) # desending order

      Name  Age  salary Team    Bonus
3  Rishabh   15   50000   DA  10000.0
0   Mathav   12   45000  CEO   4000.0
2   Lalita   14   45000  CTO   8000.0
1  Vishaka   13   30000   HR   6000.0
4      ABC   15   25000   IT   2000.0

In [ ]:
# working with data values

In [84]:
# Handing Missing Value
df

      Name  Age  salary Team    Bonus
0   Mathav   12   45000  CEO   4000.0
1  Vishaka   13   30000   HR   6000.0
2   Lalita   14   45000  CTO   8000.0
3  Rishabh   15   50000   DA  10000.0
4      ABC   15   25000   IT   2000.0

In [85]:
df.isnull()

    Name    Age  salary   Team  Bonus
0  False  False   False  False  False
1  False  False   False  False  False
2  False  False   False  False  False
3  False  False   False  False  False
4  False  False   False  False  False

In [86]:
import numpy as np

In [88]:
df.loc[df.Name=='Rishabh','salary']=np.nan

In [89]:
df

      Name  Age   salary Team    Bonus
0   Mathav   12  45000.0  CEO   4000.0
1  Vishaka   13  30000.0   HR   6000.0
2   Lalita   14  45000.0  CTO   8000.0
3  Rishabh   15      NaN   DA  10000.0
4      ABC   15  25000.0   IT   2000.0

In [90]:
df.isnull()

    Name    Age  salary   Team  Bonus
0  False  False   False  False  False
1  False  False   False  False  False
2  False  False   False  False  False
3  False  False    True  False  False
4  False  False   False  False  False

In [91]:
df.isnull().sum()

Name      0
Age       0
salary    1
Team      0
Bonus     0
dtype: int64

In [93]:
df.fillna(0)

      Name  Age   salary Team    Bonus
0   Mathav   12  45000.0  CEO   4000.0
1  Vishaka   13  30000.0   HR   6000.0
2   Lalita   14  45000.0  CTO   8000.0
3  Rishabh   15      0.0   DA  10000.0
4      ABC   15  25000.0   IT   2000.0